version: "3"
services:
  paperimage:
    container_name: "paper"
    image: ghcr.io/l3nnartt/paperimage:main
    restart: always
    ports:
      - "25565:25565"
    volumes:
      - ./plugins/:/opt/paper/plugins/
      - ./world/:/opt/paper/world/
      - ./world_the_nether/:/opt/paper/world_the_nether/
      - ./world_the_end/:/opt/paper/world_the_end/
      - ./server.properties:/opt/paper/server.properties